### ISSUE TITLE
custom metric implementation depend on length of qrels

### ISSUE THREAD

**Issue by iknoorjobs** [beir-cellar/beir#102]
Hi @thakur-nandan, Great work! Keep it up! 🍻
Just noticed one thing in the code for the custom metric ([here](https://github.com/beir-cellar/beir/blob/c3334fd5b336dba03c5e3e605a82fcfb1bdf667d/beir/retrieval/custom_metrics.py#L28)), the sum of MRR@k scores is divided by len(qrels). However, this should actually be divided by the number of queries for which MRR is computed (in your code this can be len(results)). 
Please let me know if I'm wrong. If not, I am happy to create a PR :)

Best,
Iknoor Singh

**Comment by thakur-nandan** [comment]
Hi @iknoorjobs, 

From my understanding, the evaluation should be based on the length of ``qrels``. 

For example, for a few queries in lexical search with Elasticsearch, each query is unable to return any top-k documents. In such cases, the ``results`` dictionary will not include this query. Here we must make sure the retriever is penalized by assigning MRR@k score equal to 0 for these queries present in qrels. 

We always take ``qrels`` to be the ground truth and do evaluations based on it.

Kind Regards,
Nandan Thakur
