### ISSUE TITLE
the number of queries is not as reported for some datasets?

### ISSUE THREAD

**Issue by lmh0921** [beir-cellar/beir#111]
Hello,

In some datasets, for example FIQA, if I download the datasets from https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip
the queries.jsonl contains 6648 queries, while in the paper or the readme of github, it is reported 648,
could you tell me why they are different？which one is correct

Thanks

**Comment by thakur-nandan** [comment]
Hi @lmh0921, 

The `queries.jsonl` file contains all train, development and test queries together in the single file. Refer to the `qrels/test.tsv` for the 648 queries (unique query ids) present in the test split.

Kind Regards,
Nandan Thakur

**Comment by lmh0921** [comment]
ok, got the point,
thanks @thakur-nandan !
