### ISSUE TITLE
Can't download data

### ISSUE THREAD

**Issue by TahaBinhuraib** [beir-cellar/beir#132]
The website: https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/ is down. Any idea on when we might expect it to be online?

**Comment by thakur-nandan** [comment]
Hi @TahaBinhuraib, Seems to be online now. 

Sadly, I am not affiliated with UKP anymore. I'm unable to anticipate the downtimes of the dataset. I will try to replicate the datasets and host them on another server, in incase the UKP one is found to be down.

Regards,
Nandan Thakur
