### ISSUE TITLE
Missing test.tsv in thakur/BEIR/datasets/nq-train.zip

### ISSUE THREAD

**Issue by zhiyuanpeng** [beir-cellar/beir#150]
Hi Nandan,

@thakur-nandan I can download the original train.tsv and the corresponding queries.jsonl and corpus.jsonl from https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nq-train.zip. But, there is no original test.tsv file in nq-train. The BEIR NQ corpus.jsonl is a reduced one and so, I can't use BEIR NQ's test.tsv. Do you have the test.tsv that can work with the corpus.jsonl in nq-train? Thanks.

Best Regards,
Zhiyuan.

**Comment by thakur-nandan** [comment]
Hi, check https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nq.zip for the BEIR test evaluation.

The `nq-train` folder which you use is only meant for training on NQ which contains a different corpus.
