### ISSUE TITLE
Marco triplet in train_msmarco_v2.py

### ISSUE THREAD

**Issue by WenzhengZhang** [beir-cellar/beir#82]
Thanks for sharing your work! I fould the triplets_url [here](https://github.com/beir-cellar/beir/blob/a55552db70f37102352fd5c21b4e811516659a55/examples/retrieval/training/train_msmarco_v2.py#L53) in train_msmarco_v2 is stale. Could you please share this ms marco triplets file? Thanks!

**Comment by nreimers** [comment]
@WenzhengZhang You can find an updated version of the file here:
https://huggingface.co/datasets/sentence-transformers/embedding-training-data/resolve/main/msmarco-triplets.jsonl.gz

Not that his file is in jsonl format, while the linked script expects tsv. Hence, you need to update you script how the triplets are loaded

**Comment by WenzhengZhang** [comment]
Thanks for your help!
