### ISSUE TITLE
url to msmarco triples do not exists anymore

### ISSUE THREAD

**Issue by jordane95** [beir-cellar/beir#88]
Hi,

I'm trying to run a bi-encoder on msmarco dataset. I used your `train_msmarco_v2.py` script but it appears that the [url](https://github.com/beir-cellar/beir/blob/main/examples/retrieval/training/train_msmarco_v2.py#L53) to download msmarco triples do not exists anymore...

**Comment by nreimers** [comment]
You can find the working scripts here:
https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/ms_marco
