### ISSUE TITLE
Support multi-gpu training?

### ISSUE THREAD

**Issue by jordane95** [beir-cellar/beir#90]
Hello, 

I'm trying to use your [code](https://github.com/beir-cellar/beir/blob/main/examples/retrieval/training/train_msmarco_v3.py) to train a bi-encoder on msmarco, but it seems that using a comparable batch size exceeds my GPU memory. Does your code support multi-gpu training?

**Comment by ahadda5** [comment]
@jordane95 how are you moving the data to GPU. 
  Did you move data to GPU?
 train_dataset.to(device)

**Comment by ahadda5** [comment]
My bad, cuda was not enabled and its seems BeIR uses it automatically if available 

[2022-06-06 10:29:03] INFO [beir.generation.models.auto_model.__init__:16] Use pytorch device: cuda

**Comment by thakur-nandan** [comment]
Hi @jordane95 and @ahadda5, sadly the code present in the repository uses ``Sentence-Transformers`` as a framework where multi-GPU training is yet not available. 

You can have a look at [Tevatron](https://github.com/texttron/tevatron) in case you are interested in multi-GPU training. 

Kind Regards,
Nandan Thakur

**Comment by jordane95** [comment]
Thanks! I will check it out.

**Comment by rahmanidashti** [comment]
> jordane95

Hi @jordane95, could you solve this issue? I am also running dense models on MSMARCO but it exceeds memory during encoding corpus.

**Comment by jordane95** [comment]
> > jordane95
> 
> Hi @jordane95, could you solve this issue? I am also running dense models on MSMARCO but it exceeds memory during encoding corpus.

Hi @rahmanidashti , may be you could try the [tevatron](https://github.com/texttron/tevatron) toolkit which supports chunked corpus encoding
